# Generated by Django 2.2 on 2019-05-05 13:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who', to='players.Player')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whom', to='players.Player')),
            ],
        ),
    ]
